carros = [{'id': 1, 'marca': 'Toyota', 'modelo': 'Corolla', 'ano': 2022, 'preco_diaria': 150.0, 'placa': 'H7EJx5W',
           'disponivel': True},
          {'id': 2, 'marca': 'Honda', 'modelo': 'Civic', 'ano': 2023, 'preco_diaria': 160.0, 'placa': 'k6cQmxo',
           'disponivel': True},
          {'id': 3, 'marca': 'Ford', 'modelo': 'Fusion', 'ano': 2022, 'preco_diaria': 140.0, 'placa': 'P5rDleJ',
           'disponivel': True},
          {'id': 4, 'marca': 'Volkswagen', 'modelo': 'Golf', 'ano': 2023, 'preco_diaria': 155.0, 'placa': 'P71jAFF',
           'disponivel': True},
          {'id': 5, 'marca': 'Chevrolet', 'modelo': 'Cruze', 'ano': 2022, 'preco_diaria': 145.0, 'placa': 'l4rlCkc',
           'disponivel': True},
          {'id': 6, 'marca': 'Hyundai', 'modelo': 'Elantra', 'ano': 2023, 'preco_diaria': 165.0, 'placa': 'I7Pp9iU',
           'disponivel': True},
          {'id': 7, 'marca': 'Nissan', 'modelo': 'Altima', 'ano': 2022, 'preco_diaria': 148.0, 'placa': 't59FNQV',
           'disponivel': True},
          {'id': 8, 'marca': 'Kia', 'modelo': 'Optima', 'ano': 2023, 'preco_diaria': 155.0, 'placa': 'f3qQOaa',
           'disponivel': False},
          {'id': 9, 'marca': 'Mazda', 'modelo': 'Mazda6', 'ano': 2022, 'preco_diaria': 143.0, 'placa': 'I41ht57',
           'disponivel': True},
          {'id': 10, 'marca': 'Subaru', 'modelo': 'Legacy', 'ano': 2023, 'preco_diaria': 152.0, 'placa': 'x7uKubh',
           'disponivel': True},
          {'id': 11, 'marca': 'Audi', 'modelo': 'A4', 'ano': 2022, 'preco_diaria': 170.0, 'placa': 'x3j6PQV',
           'disponivel': True},
          {'id': 12, 'marca': 'BMW', 'modelo': '3 Series', 'ano': 2023, 'preco_diaria': 180.0, 'placa': 'p68NY3u',
           'disponivel': True},
          {'id': 13, 'marca': 'Mercedes-Benz', 'modelo': 'C-Class', 'ano': 2022, 'preco_diaria': 190.0,
           'placa': 'O0u8kJy', 'disponivel': True},
          {'id': 14, 'marca': 'Lexus', 'modelo': 'IS', 'ano': 2023, 'preco_diaria': 175.0, 'placa': 'J6sLrxT',
           'disponivel': True},
          {'id': 15, 'marca': 'Tesla', 'modelo': 'Model 3', 'ano': 2022, 'preco_diaria': 250.0, 'placa': 'X6LWgJS',
           'disponivel': True},
          {'id': 16, 'marca': 'Jaguar', 'modelo': 'XE', 'ano': 2023, 'preco_diaria': 220.0, 'placa': 'O7HSNWC',
           'disponivel': True},
          {'id': 17, 'marca': 'Porsche', 'modelo': 'Panamera', 'ano': 2022, 'preco_diaria': 300.0, 'placa': 's7BewLS',
           'disponivel': False},
          {'id': 18, 'marca': 'Ferrari', 'modelo': '488 GTB', 'ano': 2023, 'preco_diaria': 1000.0, 'placa': 'N2gPmko',
           'disponivel': True},
          {'id': 19, 'marca': 'Lamborghini', 'modelo': 'Huracán', 'ano': 2022, 'preco_diaria': 1200.0,
           'placa': 'f0f5hlC', 'disponivel': True},
          {'id': 20, 'marca': 'Bugatti', 'modelo': 'Veyron', 'ano': 2023, 'preco_diaria': 2500.0, 'placa': 'I1Sz0xo',
           'disponivel': True},
          {'id': 21, 'marca': 'McLaren', 'modelo': '720S', 'ano': 2022, 'preco_diaria': 2200.0, 'placa': 'V8xL1fM',
           'disponivel': True},
          {'id': 22, 'marca': 'Aston Martin', 'modelo': 'DB11', 'ano': 2023, 'preco_diaria': 1800.0, 'placa': 'R8sct2O',
           'disponivel': True},
          {'id': 23, 'marca': 'Rolls-Royce', 'modelo': 'Phantom', 'ano': 2022, 'preco_diaria': 3500.0,
           'placa': 'm3Bx3fd', 'disponivel': True},
          {'id': 24, 'marca': 'Bentley', 'modelo': 'Continental GT', 'ano': 2023, 'preco_diaria': 2800.0,
           'placa': 'j6QUTqd', 'disponivel': True},
          {'id': 25, 'marca': 'Maserati', 'modelo': 'Quattroporte', 'ano': 2022, 'preco_diaria': 2100.0,
           'placa': 'x4BC2ah', 'disponivel': False},
          {'id': 26, 'marca': 'Volvo', 'modelo': 'S60', 'ano': 2023, 'preco_diaria': 165.0, 'placa': 'G5VT28W',
           'disponivel': False},
          {'id': 27, 'marca': 'Kia', 'modelo': 'Forte', 'ano': 2022, 'preco_diaria': 140.0, 'placa': 'l22e41q',
           'disponivel': False},
          {'id': 28, 'marca': 'Subaru', 'modelo': 'Impreza', 'ano': 2023, 'preco_diaria': 150.0, 'placa': 'V7QCoKZ',
           'disponivel': False},
          {'id': 29, 'marca': 'Audi', 'modelo': 'A3', 'ano': 2022, 'preco_diaria': 160.0, 'placa': 'q7Da4q7',
           'disponivel': False},
          {'id': 30, 'marca': 'BMW', 'modelo': '5 Series', 'ano': 2023, 'preco_diaria': 170.0, 'placa': 'X7XZpq1',
           'disponivel': False},
          {'id': 31, 'marca': 'Mercedes-Benz', 'modelo': 'E-Class', 'ano': 2022, 'preco_diaria': 180.0,
           'placa': 'Q53Hvf2', 'disponivel': False},
          {'id': 32, 'marca': 'Lexus', 'modelo': 'ES', 'ano': 2023, 'preco_diaria': 175.0, 'placa': 'r2rxQkX',
           'disponivel': False},
          {'id': 33, 'marca': 'Tesla', 'modelo': 'Model S', 'ano': 2022, 'preco_diaria': 220.0, 'placa': 'u6REwAw',
           'disponivel': False},
          {'id': 34, 'marca': 'Jaguar', 'modelo': 'XF', 'ano': 2023, 'preco_diaria': 210.0, 'placa': 'f4KsEuS',
           'disponivel': False},
          {'id': 35, 'marca': 'Porsche', 'modelo': '911', 'ano': 2022, 'preco_diaria': 320.0, 'placa': 'N0Dq50V',
           'disponivel': False},
          {'id': 36, 'marca': 'Ferrari', 'modelo': 'F8 Tributo', 'ano': 2023, 'preco_diaria': 900.0, 'placa': 'y0Y40W7',
           'disponivel': False},
          {'id': 37, 'marca': 'Lamborghini', 'modelo': 'Aventador', 'ano': 2022, 'preco_diaria': 1100.0,
           'placa': 'f4LEneA', 'disponivel': False},
          {'id': 38, 'marca': 'Bugatti', 'modelo': 'Chiron', 'ano': 2023, 'preco_diaria': 2600.0, 'placa': 'F5gTw66',
           'disponivel': False},
          {'id': 39, 'marca': 'McLaren', 'modelo': '570S', 'ano': 2022, 'preco_diaria': 2000.0, 'placa': 'H7Kk8nX',
           'disponivel': False},
          {'id': 40, 'marca': 'Aston Martin', 'modelo': 'Vantage', 'ano': 2023, 'preco_diaria': 1600.0,
           'placa': 'b0tGPUk', 'disponivel': False},
          {'id': 41, 'marca': 'Rolls-Royce', 'modelo': 'Wraith', 'ano': 2022, 'preco_diaria': 4000.0,
           'placa': 'v26XV9L', 'disponivel': False},
          {'id': 42, 'marca': 'Bentley', 'modelo': 'Bentayga', 'ano': 2023, 'preco_diaria': 2900.0, 'placa': 't52vgA8',
           'disponivel': False},
          {'id': 43, 'marca': 'Maserati', 'modelo': 'Levante', 'ano': 2022, 'preco_diaria': 2200.0, 'placa': 'j6FxqLD',
           'disponivel': False},
          {'id': 44, 'marca': 'Volvo', 'modelo': 'XC60', 'ano': 2023, 'preco_diaria': 175.0, 'placa': 'R8Dn5VS',
           'disponivel': False},
          {'id': 45, 'marca': 'Kia', 'modelo': 'Sportage', 'ano': 2022, 'preco_diaria': 140.0, 'placa': 'R9NWESg',
           'disponivel': False},
          {'id': 46, 'marca': 'Subaru', 'modelo': 'Outback', 'ano': 2023, 'preco_diaria': 155.0, 'placa': 'N1OaDzn',
           'disponivel': False},
          {'id': 47, 'marca': 'Audi', 'modelo': 'Q5', 'ano': 2022, 'preco_diaria': 165.0, 'placa': 'H0Kzq6u',
           'disponivel': True},
          {'id': 48, 'marca': 'BMW', 'modelo': 'X3', 'ano': 2023, 'preco_diaria': 175.0, 'placa': 'P0veJKk',
           'disponivel': True},
          {'id': 49, 'marca': 'Mercedes-Benz', 'modelo': 'GLC', 'ano': 2022, 'preco_diaria': 185.0, 'placa': 'X7ckQL3',
           'disponivel': True},
          {'id': 50, 'marca': 'Lexus', 'modelo': 'RX', 'ano': 2023, 'preco_diaria': 180.0, 'placa': 'F5ni3UE',
           'disponivel': True},
          {'id': 51, 'marca': 'Tesla', 'modelo': 'Model X', 'ano': 2022, 'preco_diaria': 230.0, 'placa': 'q9mRtNu',
           'disponivel': True},
          {'id': 52, 'marca': 'Jaguar', 'modelo': 'F-PACE', 'ano': 2023, 'preco_diaria': 210.0, 'placa': 'b6rRmzA',
           'disponivel': True},
          {'id': 53, 'marca': 'Porsche', 'modelo': 'Cayenne', 'ano': 2022, 'preco_diaria': 340.0, 'placa': 'K1Bqaei',
           'disponivel': True},
          {'id': 54, 'marca': 'Ferrari', 'modelo': 'Portofino', 'ano': 2023, 'preco_diaria': 800.0, 'placa': 'i7TnsHy',
           'disponivel': True},
          {'id': 55, 'marca': 'Lamborghini', 'modelo': 'Urus', 'ano': 2022, 'preco_diaria': 1000.0, 'placa': 'Y97j8u2',
           'disponivel': True},
          {'id': 56, 'marca': 'Bugatti', 'modelo': 'Divo', 'ano': 2023, 'preco_diaria': 2700.0, 'placa': 'p7vBGyl',
           'disponivel': True},
          {'id': 57, 'marca': 'McLaren', 'modelo': '600LT', 'ano': 2022, 'preco_diaria': 2100.0, 'placa': 'C86iOoh',
           'disponivel': True},
          {'id': 58, 'marca': 'Aston Martin', 'modelo': 'Rapide', 'ano': 2023, 'preco_diaria': 1700.0,
           'placa': 'M10UFjK', 'disponivel': True},
          {'id': 59, 'marca': 'Rolls-Royce', 'modelo': 'Ghost', 'ano': 2022, 'preco_diaria': 4200.0, 'placa': 'h2PD5DB',
           'disponivel': True},
          {'id': 60, 'marca': 'Bentley', 'modelo': 'Mulsanne', 'ano': 2023, 'preco_diaria': 3100.0, 'placa': 'e0yUKYi',
           'disponivel': True},
          {'id': 61, 'marca': 'Maserati', 'modelo': 'GranTurismo', 'ano': 2022, 'preco_diaria': 2400.0,
           'placa': 'W0QXSOr', 'disponivel': True},
          {'id': 62, 'marca': 'Volvo', 'modelo': 'XC90', 'ano': 2023, 'preco_diaria': 185.0, 'placa': 'n08OtVZ',
           'disponivel': True},
          {'id': 63, 'marca': 'Kia', 'modelo': 'Sorento', 'ano': 2022, 'preco_diaria': 150.0, 'placa': 'y7OeCIj',
           'disponivel': True},
          {'id': 64, 'marca': 'Subaru', 'modelo': 'Crosstrek', 'ano': 2023, 'preco_diaria': 160.0, 'placa': 'G8beCGn',
           'disponivel': True},
          {'id': 65, 'marca': 'Audi', 'modelo': 'Q7', 'ano': 2022, 'preco_diaria': 175.0, 'placa': 'q9GX4vK',
           'disponivel': True},
          {'id': 66, 'marca': 'BMW', 'modelo': 'X5', 'ano': 2023, 'preco_diaria': 190.0, 'placa': 'N0tqJ8f',
           'disponivel': True},
          {'id': 67, 'marca': 'Mercedes-Benz', 'modelo': 'GLE', 'ano': 2022, 'preco_diaria': 200.0, 'placa': 'c43cw7S',
           'disponivel': True},
          {'id': 68, 'marca': 'Lexus', 'modelo': 'NX', 'ano': 2023, 'preco_diaria': 195.0, 'placa': 'N150nfc',
           'disponivel': True},
          {'id': 69, 'marca': 'Tesla', 'modelo': 'Model Y', 'ano': 2022, 'preco_diaria': 240.0, 'placa': 'J9dvjWG',
           'disponivel': True},
          {'id': 70, 'marca': 'Jaguar', 'modelo': 'I-PACE', 'ano': 2023, 'preco_diaria': 220.0, 'placa': 'T99by6k',
           'disponivel': True},
          {'id': 71, 'marca': 'Porsche', 'modelo': 'Macan', 'ano': 2022, 'preco_diaria': 330.0, 'placa': 'g95C95A',
           'disponivel': True},
          {'id': 72, 'marca': 'Ferrari', 'modelo': '812 Superfast', 'ano': 2023, 'preco_diaria': 950.0,
           'placa': 'R4blSfr', 'disponivel': True},
          {'id': 73, 'marca': 'Lamborghini', 'modelo': 'Sian', 'ano': 2022, 'preco_diaria': 1050.0, 'placa': 'z8rNCbm',
           'disponivel': True},
          {'id': 74, 'marca': 'Bugatti', 'modelo': 'La Voiture Noire', 'ano': 2023, 'preco_diaria': 2800.0,
           'placa': 'u37SsMG', 'disponivel': True},
          {'id': 75, 'marca': 'McLaren', 'modelo': 'GT', 'ano': 2022, 'preco_diaria': 2150.0, 'placa': 'I57Lnal',
           'disponivel': True},
          {'id': 76, 'marca': 'Aston Martin', 'modelo': 'DBS Superleggera', 'ano': 2023, 'preco_diaria': 1750.0,
           'placa': 'h13FuAP', 'disponivel': True},
          {'id': 77, 'marca': 'Rolls-Royce', 'modelo': 'Dawn', 'ano': 2022, 'preco_diaria': 4400.0, 'placa': 'y9x0niE',
           'disponivel': True},
          {'id': 78, 'marca': 'Bentley', 'modelo': 'Bentley', 'ano': 2023, 'preco_diaria': 3200.0, 'placa': 'V1MvGrF',
           'disponivel': True},
          {'id': 79, 'marca': 'Maserati', 'modelo': 'Ghibli', 'ano': 2022, 'preco_diaria': 2300.0, 'placa': 'T9ljsCW',
           'disponivel': True},
          {'id': 80, 'marca': 'Volvo', 'modelo': 'V60', 'ano': 2023, 'preco_diaria': 190.0, 'placa': 'H5hjgj0',
           'disponivel': True},
          {'id': 81, 'marca': 'Kia', 'modelo': 'K5', 'ano': 2022, 'preco_diaria': 145.0, 'placa': 'D38dQYZ',
           'disponivel': True},
          {'id': 82, 'marca': 'Subaru', 'modelo': 'Forester', 'ano': 2023, 'preco_diaria': 155.0, 'placa': 'S7YDHnq',
           'disponivel': True},
          {'id': 83, 'marca': 'Audi', 'modelo': 'SQ5', 'ano': 2022, 'preco_diaria': 175.0, 'placa': 'S8cXOdu',
           'disponivel': True},
          {'id': 84, 'marca': 'BMW', 'modelo': 'X7', 'ano': 2023, 'preco_diaria': 200.0, 'placa': 'k88F8eE',
           'disponivel': True},
          {'id': 85, 'marca': 'Mercedes-Benz', 'modelo': 'GLA', 'ano': 2022, 'preco_diaria': 205.0, 'placa': 't1Fvft6',
           'disponivel': True},
          {'id': 86, 'marca': 'Lexus', 'modelo': 'UX', 'ano': 2023, 'preco_diaria': 200.0, 'placa': 'h9nZAvJ',
           'disponivel': True},
          {'id': 87, 'marca': 'Tesla', 'modelo': 'Roadster', 'ano': 2022, 'preco_diaria': 250.0, 'placa': 'u6E3wtu',
           'disponivel': True},
          {'id': 88, 'marca': 'Jaguar', 'modelo': 'F-TYPE', 'ano': 2023, 'preco_diaria': 230.0, 'placa': 'k4HGUqz',
           'disponivel': True},
          {'id': 89, 'marca': 'Porsche', 'modelo': 'Taycan', 'ano': 2022, 'preco_diaria': 360.0, 'placa': 'J6zZO5K',
           'disponivel': True},
          {'id': 90, 'marca': 'Ferrari', 'modelo': 'Roma', 'ano': 2023, 'preco_diaria': 850.0, 'placa': 'h4uVmQt',
           'disponivel': True},
          {'id': 91, 'marca': 'Lamborghini', 'modelo': 'Sián FKP 37', 'ano': 2022, 'preco_diaria': 1100.0,
           'placa': 'O7Damm4', 'disponivel': True},
          {'id': 92, 'marca': 'Bugatti', 'modelo': 'Centodieci', 'ano': 2023, 'preco_diaria': 3000.0,
           'placa': 'i5cKxUt', 'disponivel': True},
          {'id': 93, 'marca': 'McLaren', 'modelo': '675LT', 'ano': 2022, 'preco_diaria': 2000.0, 'placa': 'J7ptFZK',
           'disponivel': True},
          {'id': 94, 'marca': 'Aston Martin', 'modelo': 'Valhalla', 'ano': 2023, 'preco_diaria': 1900.0,
           'placa': 'h1IsTsF', 'disponivel': True},
          {'id': 95, 'marca': 'Rolls-Royce', 'modelo': 'Cullinan', 'ano': 2022, 'preco_diaria': 4800.0,
           'placa': 'E1ag80O', 'disponivel': True},
          {'id': 96, 'marca': 'Bentley', 'modelo': 'Flying Spur', 'ano': 2023, 'preco_diaria': 3300.0,
           'placa': 'v9Ptdju', 'disponivel': True},
          {'id': 97, 'marca': 'Maserati', 'modelo': 'MC20', 'ano': 2022, 'preco_diaria': 2500.0, 'placa': 'Y8bbZjX',
           'disponivel': True},
          {'id': 98, 'marca': 'Volvo', 'modelo': 'V90', 'ano': 2023, 'preco_diaria': 200.0, 'placa': 'R1srlCg',
           'disponivel': True},
          {'id': 99, 'marca': 'Kia', 'modelo': 'Telluride', 'ano': 2022, 'preco_diaria': 155.0, 'placa': 't8pLFnI',
           'disponivel': True},
          {'id': 100, 'marca': 'Subaru', 'modelo': 'Ascent', 'ano': 2023, 'preco_diaria': 165.0, 'placa': 'G9WRMgA',
           'disponivel': True}]
